name: tfasoft_mobile
description: TFAsoft mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  provider: ^6.0.3
  clipboard: ^0.1.3
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/wallpaper_1.jpg
    - assets/images/wallpaper_2.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#0088CC"
    theme_color: "#0088CC"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48